version: "3"
services: 
  postgres-db:
    image: postgres
    container_name: postgres-container
    volumes: 
     - ./data:/var/lib/postgresql/data/
    environment:
     POSTGRES_PASSWORD: root

  pgadmin-servie:
    image: dpage/pgadmin4
    ports: 
     - "8089:80"
    environment: 
     PGADMIN_DEFAULT_EMAIL: some@one.com
     PGADMIN_DEFAULT_PASSWORD: root
     